---
# Install tools to build universal-ctags
# http://docs.ctags.io/en/latest/autotools.html

- name: install ctags pre-requisites
  apt:
    pkg:
      - pkg-config
      - autoconf
      - automake
      - python3-docutils
      - libseccomp-dev
      - libjansson-dev
      - libyaml-dev
      - libxml2-dev

